#generate ssl cert
#AWX_HOST="awx.example.com"
#/opt/homebrew/opt/openssl@3/bin/openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -out ./base/tls.crt -keyout ./base/tls.key -subj "/CN=${AWX_HOST}/O=${AWX_HOST}" -addext "subjectAltName = DNS:${AWX_HOST}"
#problem with ingress controller
#customize resource limits in base awx.yaml
#show all image path in namespace
#kubectl get pods -o jsonpath="{.items[*].spec.containers[*].image}" |\ 
# tr -s '[[:space:]]' '\n' |\
# sort |\
# uniq -c
#    1 docker.io/redis:latest
#    1 localhost:6000/awx-operator:0.21.0
#    1 localhost:6000/kube-rbac-proxy:v0.8.0
#    1 postgres:12
#    1 quay.io/ansible/awx-ee:latest
#    2 quay.io/ansible/awx:21.0.0
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: autovm-ns

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx-postgres
      - port=5432
      - database=awx
      - username=awx
      - password=Ansible123!
      - type=managed

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=Ansible123!

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - awx.yaml

# images:
# - name: quay.io/centos/centos
#   newName: localhost:6000/centos
#   newTag: stream8
# - name: quay.io/ansible/awx-ee
#   newName: localhost:6000/awx-ee
#   newTag: latest
# - name: redis
#   newName: localhost:6000/redis
#   newTag: latest
# - name: quay.io/ansible/awx
#   newName: localhost:6000/awx
#   newTag: 21.0.0
# - name: postgres
#   newName: localhost:6000/postgres
#   newTag: 12
# - name: httpd
#   newName: localhost:6000/httpd
#   newTag: latest
