apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=0.21.0

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.21.0

# Specify a custom namespace in which to install AWX
namespace: autovm-ns

images:
- name: quay.io/ansible/awx-operator
  newName: localhost:6000/awx-operator
  newTag: 0.21.0
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: localhost:6000/kube-rbac-proxy 
  newTag: v0.8.0
